config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
    confirmations: 'admins/confirmations',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    unlocks: 'admins/unlocks',
  }
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'root/index'
  root 'root#index'
  
  get 'about/index'
  
  get 'contact/index'
  
  get 'portfolio/index'
  get 'portfolio/pf01'
  get 'portfolio/pf02'
  get 'portfolio/pf03'
  
  resources :posts
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html　lang="ja">
<head>
  <meta charset="utf-8">
  <title><%= @page_title %> | komorikomasha</title>
  <meta name="description" content="<%= content_description(request.path_info) %>">
  <%= stylesheet_link_tag    'normalize', 'style', 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Fauna+One' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="common/js/jquery.bxslider/jquery.bxslider.js"></script>
  <link rel="stylesheet" href="common/js/jquery.bxslider/jquery.bxslider.css">

  <script>
    $(document).ready(function(){
      $('.bxslider').bxSlider({
        auto: true,
        speed: 1000,
        pause: 4000
      });
    });
  </script>
</head>

<body>
<div id="page">
  <div class="navbar">
    <!--navbar-->
    <div class="navbar-text">
      <% if admin_signed_in? %>
        Logged in as <strong><%= current_admin.email %></strong>.
        <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    
    <div class="navbar-notice">
      <% if notice %>
        <p class="notice"><%= notice %><p/>
      <% elsif alert %>
        <p class="alert"><%= alert %><p/>
      <% end %>
    </div>
    <!--end navbar-->
  </div>
  
  <header id="pageHead">
    <%= render :partial => 'shared/header' %>
  </header>

  <div class="topicPath">
    <p><%= breadcrumbs separator: " &gt; " %></p>
  </div>

  <div id="pageBody">

    <%= yield %>
    
  </div>

  <p class="pagetop"><a href="#page">ページの先頭へ戻る</a></p>

  <footer id="pageFoot">
    <%= render :partial => 'shared/footer' %>
  </footer>

</div>
</body>
</html>